(()=>{'use strict';
const NS='http://www.w3.org/2000/svg',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const drawing=$('#drawing'),sides=$('#sides'),radius=$('#radius'),sections=['#derivation','#workbook','#errors','#scale'].map($);
const checkpoints={predicted:false,manipulated:false,revealed:false,audited:false,scaled:false},solved=new Set();
let derivStep=0,mode='regions',initialN=12,initialRadius=1;
const fmt=(v,d=4)=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
const pct=v=>new Intl.NumberFormat('pt-BR',{style:'percent',minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const svg=(name,attrs={},text='')=>{const n=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,v));if(text)n.textContent=text;return n};
const polar=(cx,cy,r,a)=>[cx+r*Math.cos(a),cy+r*Math.sin(a)];
const poly=(cx,cy,r,n,start)=>Array.from({length:n},(_,i)=>polar(cx,cy,r,start+2*Math.PI*i/n));
const ain=(n,r=1)=>(n*r*r/2)*Math.sin(2*Math.PI/n),aout=(n,r=1)=>n*r*r*Math.tan(Math.PI/n),pin=(n,r=1)=>2*n*r*Math.sin(Math.PI/n),pout=(n,r=1)=>2*n*r*Math.tan(Math.PI/n);
const css=name=>getComputedStyle(document.documentElement).getPropertyValue(name);
function progress(){const total=(checkpoints.predicted?1:0)+(checkpoints.manipulated?1:0)+(checkpoints.revealed?1:0)+solved.size+(checkpoints.audited?1:0)+(checkpoints.scaled?1:0);const capped=Math.min(9,total);$('#progress-fill').style.width=`${capped/9*100}%`;$('#progress-text').textContent=`${capped}/9`;$('.track').setAttribute('aria-valuenow',capped);$('#finish-status').textContent=capped===9?'9/9. A área foi vista, construída, testada, escalada e auditada.':`${capped}/9 movimentos concluídos.`}
function label(g,x,y,t,a='start',size=18,color='currentColor'){g.append(svg('text',{x,y,'text-anchor':a,'font-family':'system-ui','font-size':size,'font-weight':800,fill:color},t))}
function canvas(id,h){const c=$(id),r=c.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,r.width*dpr);c.height=h*dpr;const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,h);return[x,r.width,h]}
function renderGeometry(){const n=+sides.value,rho=+radius.value,t=Math.PI/n,cx=320,cy=340,R=110+25*rho,outR=R/Math.cos(t),start=-Math.PI/2-t,Ai=ain(n,rho),Ac=Math.PI*rho*rho,Ao=aout(n,rho),ap=rho*Math.cos(t);
$('#sides-output').value=$('#sides-output').textContent=String(n);$('#radius-output').value=$('#radius-output').textContent=fmt(rho,2);$('#a-in').textContent=fmt(Ai);$('#a-circle').textContent=fmt(Ac);$('#a-out').textContent=fmt(Ao);$('#apothem').textContent=fmt(ap);$('#err-in').textContent=fmt(Ac-Ai);$('#err-out').textContent=fmt(Ao-Ac);$('#area-error-ratio').textContent=fmt((Ac-Ai)/(Ao-Ac));$('#coverage').textContent=pct(Ai/Ac);
drawing.replaceChildren();const inner=poly(cx,cy,R,n,start),outer=poly(cx,cy,outR,n,start);
drawing.append(svg('polygon',{points:outer.map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--accent2) 18%,transparent)',stroke:'var(--accent2)','stroke-width':4}));
drawing.append(svg('circle',{cx,cy,r:R,fill:'color-mix(in srgb,var(--focus) 10%,var(--bg))',stroke:'currentColor','stroke-width':3,'stroke-dasharray':'4 8'}));
drawing.append(svg('polygon',{points:inner.map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--accent) 30%,transparent)',stroke:'var(--accent)','stroke-width':4}));
if(mode==='fan'||mode==='errors'){inner.forEach(p=>drawing.append(svg('line',{x1:cx,y1:cy,x2:p[0],y2:p[1],stroke:'var(--accent)','stroke-width':mode==='fan'?2:1,opacity:mode==='fan'?.75:.35})));outer.forEach(p=>drawing.append(svg('line',{x1:cx,y1:cy,x2:p[0],y2:p[1],stroke:'var(--accent2)','stroke-width':mode==='fan'?2:1,opacity:mode==='fan'?.55:.25})))}
if(mode==='errors'){label(drawing,cx-R*.55,cy-R*.72,'falta','middle',18,'var(--focus)');label(drawing,cx+outR*.62,cy-outR*.36,'sobra','middle',18,'var(--accent2)')}
const M=polar(cx,cy,R*Math.cos(t),-Math.PI/2),V=polar(cx,cy,R,-Math.PI/2+t);drawing.append(svg('polygon',{points:[[cx,cy],M,V].map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--focus) 22%,transparent)',stroke:'var(--focus)','stroke-width':4}));drawing.append(svg('circle',{cx:M[0],cy:M[1],r:6,fill:'var(--focus)'}));label(drawing,M[0]+15,M[1]+18,'a');label(drawing,(cx+V[0])/2+10,(cy+V[1])/2,'ρ');label(drawing,cx,38,`n=${n} · ρ=${fmt(rho,2)}`,'middle');label(drawing,cx,662,'Ain < πρ² < Aout','middle',20);renderAreaChart();if(checkpoints.revealed)renderDeriv()}
function renderAreaChart(){const[x,W,H]=canvas('#area-chart',230),p=28,nNow=+sides.value,rho=+radius.value,r2=rho*rho,mapX=n=>p+(n-3)/93*(W-2*p),yMin=1.2*r2,yMax=5.35*r2,mapY=v=>H-p-(v-yMin)/(yMax-yMin)*(H-2*p);x.strokeStyle=css('--line');x.beginPath();x.moveTo(p,p);x.lineTo(p,H-p);x.lineTo(W-p,H-p);x.stroke();const draw=(fn,color)=>{x.strokeStyle=color;x.lineWidth=2;x.beginPath();for(let n=3;n<=96;n++){const X=mapX(n),Y=mapY(fn(n,rho));n===3?x.moveTo(X,Y):x.lineTo(X,Y)}x.stroke()};draw(ain,css('--accent'));draw((_,r)=>Math.PI*r*r,css('--ink'));draw(aout,css('--accent2'));[[ain(nNow,rho),css('--accent')],[Math.PI*r2,css('--ink')],[aout(nNow,rho),css('--accent2')]].forEach(([v,c])=>{x.fillStyle=c;x.beginPath();x.arc(mapX(nNow),mapY(v),5,0,Math.PI*2);x.fill()});x.fillStyle=css('--ink');x.font='700 12px system-ui';x.fillText('3',p-3,H-7);x.fillText('96',W-p-15,H-7);x.fillText('fora',W-55,18);x.fillText('círculo',W-55,40);x.fillText('dentro',W-55,62)}
function updateReveal(){if(!checkpoints.predicted){$('#reveal').textContent='1. Faça uma aposta acima';$('#reveal-status').textContent='Depois da aposta, o botão abre a construção inteira.'}else if(!checkpoints.revealed){$('#reveal').textContent='2. Abrir o leque';$('#reveal-status').textContent=checkpoints.manipulated?'Aposta e experimento feitos.':'Aposta feita. Manipular ajuda, mas não bloqueia.'}else{$('#reveal').textContent='Leque aberto abaixo ↓';$('#reveal-status').textContent='Agora existem derivação, exercícios, erro, escala, curiosidades e prova.'}}
$$('[data-prediction]').forEach(b=>b.onclick=()=>{$$('[data-prediction]').forEach(q=>q.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');checkpoints.predicted=true;$('#prediction-feedback').textContent=b.dataset.prediction==='less'?'A aposta coincide com o dodecágono: a área coberta é cerca de 95,5%. Agora descubra por quê.':'Aposta registrada. O apótema dará o veredito.';updateReveal();progress()});
function changed(){if(+sides.value!==initialN||+radius.value!==initialRadius)checkpoints.manipulated=true;renderGeometry();progress()}
sides.oninput=changed;radius.oninput=changed;$$('[data-n]').forEach(b=>b.onclick=()=>{sides.value=b.dataset.n;changed()});$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(q=>q.setAttribute('aria-pressed',String(q===b)));checkpoints.manipulated=true;renderGeometry();progress()});
$('#reveal').onclick=()=>{if(!checkpoints.predicted){$('#bet').scrollIntoView({behavior:'smooth',block:'start'});$('#prediction-feedback').textContent='Escolha uma hipótese. Ela pode morrer depois; precisa apenas nascer antes.';return}sections.forEach(s=>s.hidden=false);checkpoints.revealed=true;updateReveal();renderDeriv();renderErrors();renderScale();progress();$('#derivation').scrollIntoView({behavior:'smooth',block:'start'})};
const chain=$$('#chain>li'),dots=$('#step-dots');chain.forEach((_,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1);b.setAttribute('aria-label',`Ir ao passo ${i+1}`);b.onclick=()=>{derivStep=i;renderDeriv()};dots.append(b)});
function renderDeriv(){chain.forEach((li,i)=>li.hidden=i!==derivStep);$$('#step-dots button').forEach((b,i)=>{if(i===derivStep)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current')});$('#prev-step').disabled=derivStep===0;$('#next-step').disabled=derivStep===8;$('#step-status').textContent=`Passo ${derivStep+1} de 9${derivStep===8?' — cerco de áreas fechado.':''}`;$('#deriv-result').hidden=derivStep!==8;
const g=$('#deriv-drawing'),cx=250,cy=250,R=160,n=+sides.value,t=Math.PI/n,start=-Math.PI/2-t,outR=R/Math.cos(t),s=derivStep,inner=poly(cx,cy,R,n,start),outer=poly(cx,cy,outR,n,start),M=polar(cx,cy,R*Math.cos(t),-Math.PI/2),V=polar(cx,cy,R,-Math.PI/2+t),T=polar(cx,cy,R,-Math.PI/2),E=polar(cx,cy,outR,-Math.PI/2+t);g.replaceChildren();
const captions=['O centro reparte o polígono interno em n triângulos congruentes.','Um triângulo recebe base ℓin e altura a.','A área do triângulo é base × altura ÷ 2.','A soma das bases é o perímetro: Ain=Pin·a/2.','O triângulo fundamental fornece seno e cosseno.','A identidade de ângulo duplo comprime o produto.','No exterior, ρ já é a altura de cada triângulo.','O perímetro externo vezes ρ/2 fecha Aout.','Inclusão geométrica: interno < círculo < externo.'];$('#deriv-caption').textContent=captions[s];
if(s<=5){g.append(svg('polygon',{points:inner.map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--accent) 12%,transparent)',stroke:'var(--accent)','stroke-width':3}));inner.forEach(p=>g.append(svg('line',{x1:cx,y1:cy,x2:p[0],y2:p[1],stroke:'var(--accent)','stroke-width':1.6,opacity:.7})));if(s>=1){g.append(svg('polygon',{points:[[cx,cy],M,V].map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--focus) 24%,transparent)',stroke:'var(--focus)','stroke-width':4}));label(g,(M[0]+V[0])/2+4,(M[1]+V[1])/2-9,'ℓin/2');label(g,(cx+M[0])/2-10,(cy+M[1])/2,'a','end');label(g,(cx+V[0])/2+10,(cy+V[1])/2,'ρ')}if(s===2)label(g,cx,474,'△ = ℓin·a/2','middle',20);if(s===3)label(g,cx,474,'Ain = Pin·a/2','middle',20);if(s===4)label(g,cx,474,'Ain = nρ² sen(π/n) cos(π/n)','middle',18);if(s===5)label(g,cx,474,'Ain = (nρ²/2) sen(2π/n)','middle',19)}
if(s>=6&&s<=7){g.append(svg('polygon',{points:outer.map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--accent2) 10%,transparent)',stroke:'var(--accent2)','stroke-width':3}));outer.forEach(p=>g.append(svg('line',{x1:cx,y1:cy,x2:p[0],y2:p[1],stroke:'var(--accent2)','stroke-width':1.3,opacity:.5})));g.append(svg('polygon',{points:[[cx,cy],T,E].map(p=>p.join(',')).join(' '),fill:'color-mix(in srgb,var(--focus) 22%,transparent)',stroke:'var(--focus)','stroke-width':4}));label(g,(cx+T[0])/2-10,(cy+T[1])/2,'ρ','end');label(g,(T[0]+E[0])/2+5,(T[1]+E[1])/2-8,'ℓout/2');if(s===7)label(g,cx,474,'Aout = nρ² tg(π/n)','middle',20)}
if(s===8){g.append(svg('polygon',{points:outer.map(p=>p.join(',')).join(' '),fill:'none',stroke:'var(--accent2)','stroke-width':4}));g.append(svg('circle',{cx,cy,r:R,fill:'none',stroke:'currentColor','stroke-width':3,'stroke-dasharray':'4 8'}));g.append(svg('polygon',{points:inner.map(p=>p.join(',')).join(' '),fill:'none',stroke:'var(--accent)','stroke-width':4}));label(g,cx,474,'Ain < πρ² < Aout','middle',22)}}
$('#prev-step').onclick=()=>{derivStep=Math.max(0,derivStep-1);renderDeriv()};$('#next-step').onclick=()=>{derivStep=Math.min(8,derivStep+1);renderDeriv()};
const answers={dodec:'3',hex:'10.3923',asym:'2',scale:'4'},messages={dodec:'Exato: (12/2)·sen(π/6)=6·1/2=3.',hex:'Exato: A=P·a/2=12√3/2=6√3≈10,3923.',asym:'Exato: a falta interna tende a ser duas vezes a sobra externa.',scale:'Exato: áreas e erros absolutos carregam ρ²; dobrar ρ multiplica por 4.'};
$$('[data-ex]').forEach(b=>b.onclick=()=>{const k=b.dataset.ex,ok=b.dataset.answer===answers[k],f=$(`[data-feedback="${k}"]`);f.textContent=ok?messages[k]:'Ainda não. Volte à figura ou abra a pista.';if(ok&&!solved.has(k)){solved.add(k);$$(`[data-ex="${k}"]`).forEach(q=>{q.disabled=true;q.setAttribute('aria-pressed',q===b?'true':'false')});progress()}});
function renderErrors(){const n=+$('#error-n').value,A=Math.PI,Ai=ain(n),Ao=aout(n),ei=A-Ai,eo=Ao-A,ep=1-pin(n)/(2*Math.PI),ea=ei/A;$('#error-n-output').value=$('#error-n-output').textContent=String(n);$('#audit-in').textContent=fmt(ei,6);$('#audit-out').textContent=fmt(eo,6);$('#audit-area-ratio').textContent=fmt(ei/eo,4);$('#audit-cross-ratio').textContent=fmt(ea/ep,4);$('#error-feedback').textContent=`Em n=${n}, a razão falta/sobra é ${fmt(ei/eo,3)}; em n maior ela se aproxima de 2.`;const[x,W,H]=canvas('#error-chart',320),L=42,R=W-20,T=18,B=H-38,mapX=k=>L+(Math.log(k)-Math.log(6))/(Math.log(384)-Math.log(6))*(R-L),vals=[];for(let k=6;k<=384;k++)vals.push(Math.PI-ain(k),aout(k)-Math.PI);const lo=Math.log10(Math.min(...vals)),hi=Math.log10(Math.max(...vals)),mapY=v=>B-(Math.log10(v)-lo)/(hi-lo)*(B-T);x.strokeStyle=css('--line');x.beginPath();x.moveTo(L,T);x.lineTo(L,B);x.lineTo(R,B);x.stroke();const draw=(fn,c)=>{x.strokeStyle=c;x.lineWidth=2;x.beginPath();for(let k=6;k<=384;k++){const X=mapX(k),Y=mapY(fn(k));k===6?x.moveTo(X,Y):x.lineTo(X,Y)}x.stroke()};draw(k=>Math.PI-ain(k),css('--accent'));draw(k=>aout(k)-Math.PI,css('--accent2'));const guide0=Math.PI-ain(12);x.strokeStyle=css('--focus');x.setLineDash([6,6]);x.beginPath();for(let k=12;k<=384;k++){const v=guide0*(12/k)**2;k===12?x.moveTo(mapX(k),mapY(v)):x.lineTo(mapX(k),mapY(v))}x.stroke();x.setLineDash([]);x.fillStyle=css('--ink');x.font='700 12px system-ui';x.fillText('6',L-3,H-8);x.fillText('384',R-22,H-8);x.fillText('falta interna',L+8,18);x.fillText('sobra externa',L+8,38);x.fillText('guia n⁻²',L+8,58);checkpoints.audited=true;progress()}
$('#error-n').oninput=renderErrors;
function renderScale(){const[x,W,H]=canvas('#scale-chart',320),n=+sides.value,r=+radius.value,labels=['círculo','falta','sobra'],v1=[Math.PI*r*r,Math.PI*r*r-ain(n,r),aout(n,r)-Math.PI*r*r],r2=2*r,v2=[Math.PI*r2*r2,Math.PI*r2*r2-ain(n,r2),aout(n,r2)-Math.PI*r2*r2],max=Math.max(...v2),baseY=H-42,group=W/3;x.strokeStyle=css('--line');x.beginPath();x.moveTo(24,baseY);x.lineTo(W-18,baseY);x.stroke();labels.forEach((lab,i)=>{const center=group*(i+.5),w=Math.min(34,group*.18),h1=v1[i]/max*(H-82),h2=v2[i]/max*(H-82);x.fillStyle=css('--accent');x.fillRect(center-w-3,baseY-h1,w,h1);x.fillStyle=css('--accent2');x.fillRect(center+3,baseY-h2,w,h2);x.fillStyle=css('--ink');x.font='700 12px system-ui';x.textAlign='center';x.fillText(lab,center,H-18);x.fillText('ρ',center-w/2-3,baseY-h1-7);x.fillText('2ρ',center+w/2+3,baseY-h2-7)});x.textAlign='start';checkpoints.scaled=true;progress()}
window.addEventListener('resize',()=>{renderGeometry();if(!$('#errors').hidden)renderErrors();if(!$('#scale').hidden)renderScale()});$('#restart').onclick=()=>location.reload();renderGeometry();updateReveal();progress();
})();